apiVersion: extensions/v1beta1
kind: Deployment 
metadata: 
  name: kafka-slave
spec: 
  replicas: 2
  template: 
    metadata: 
      labels: 
        name: kafka-slave
    spec: 
      containers: 
        - name: kafka-slave
          image: wurstmeister/kafka
          env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: kafka-slave
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_NUM_PARTITIONS
            value: "5"
          ports:
          - containerPort: 9092